### ISSUE TITLE
Проблемы с getSeqNo()

### ISSUE THREAD

**Issue by 1devout0** [tonwhales/ton#4]
Всем привет. Создаю кошелёк, получается. Делаю wallet.wallet.getSeqNo() - вываливается в такую ошибку:
```
(node:22645) UnhandledPromiseRejectionWarning: Error: Mailformed response: Expecting one of:
    number
    string
at balance but instead got: undefined, Expecting { @type: "ton.blockIdExt", workchain: number, shard: string, seqno: number, root_hash: string, file_hash: string } at block_id but instead got: undefined, Expecting string at code but instead got: 500, Expecting string at data but instead got: undefined, Expecting { @type: "internal.transactionId", lt: string, hash: string } at last_transaction_id but instead got: undefined, Expecting number at sync_utime but instead got: undefined
    at HttpApi.doCall (/tonwhales/node_modules/ton/dist/client/api/HttpApi.js:259:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at TonClient.getContractState (/tonwhales/node_modules/ton/dist/client/TonClient.js:216:20)
    at TonClient.isContractDeployed (/tonwhales/node_modules/ton/dist/client/TonClient.js:209:17)
    at Function.findActiveBySecretKey (/tonwhales/node_modules/ton/dist/client/Wallet.js:116:28)
    at Function.findBestBySecretKey (/tonwhales/node_modules/ton/dist/client/Wallet.js:126:25)
    at a (/tonwhales/index.ts:33:19)
```
В чём может быть проблема? Как бороться?

**Comment by 1devout0** [comment]
Ответ от Toncenter:

```
{
    "ok": true,
    "result": {
        "@type": "error",
        "code": 500,
        "message": "VALIDATE_ACCOUNT_STATEshard block id (-2147483648,0000000000000000,0):1022FC020000000023010000000000009D2C00000000000030E254667B7F0000:90D554667B7F00007BE9560000000000DAB4F400000000000A0100007B7F0000 in answer is invalid",
        "@extra": "1642262939.8276303:0.020922029986644497",
        "state": "uninitialized"
    },
    "id": "1"
}
```
